# Change these first
owner: Turtle84375
repo: status

sites:
  - name: Turtle84375 (main domain)
    url: https://turtle84375.me
  - name: TurtleChat (webapp)
    url: https://turtlechat.herokuapp.com
  - name: TurtleChat (subdomain redirect)
    url: https://chat.turtle84375.tk
  - name: Turtle84375 Status (this site)
    url: https://status.turtle84375.me

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.turtle84375.me
  # baseUrl: /your-repo-name
  favicon: https://raw.githubusercontent.com/Turtle84375/turtle84375.me/main/favicon.ico
  logoUrl: https://raw.githubusercontent.com/Turtle84375/turtle84375.me/main/assets/logo.png
  name: Turtle84375 Status
  introTitle: "**Website status page** for all Turtle84375 domains."
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/Turtle84375/status).
  navbar:
    - title: Home
      href: https://turtle84375.me
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more!
# See https://upptime.js.org/docs/configuration
